### ISSUE TITLE
[BUG] Deletes commercial_parnter_id

### ISSUE THREAD

**Issue by edsersolis** [alekglez/odoo-v10#1]
We were experiencing an issue where the commercial_partner_id was getting deleted every time a contact (individual) was added to a partner (company).

Doing some testing we found out that this module was the one causing the issue. Do you know why it could be causing this?

You can see the behavior in this video (first how it should work, second how it works when this module is installed): https://youtu.be/p7qxvOutl_g

**Comment by alekglez** [comment]
What module are you talking about? 
In any module published in my repository there is reference or inheritance with the class ‘res.partner’...
Could you be more specific?

 

 

De: Edser Solís [mailto:notifications@github.com] 
Enviado el: lunes, 29 de mayo de 2017 3:24
Para: alekglez/odoo-v10 <odoo-v10@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [alekglez/odoo-v10] [BUG] Deletes commercial_parnter_id (#1)

 

We were experiencing an issue where the commercial_partner_id was getting deleted every time a contact (individual) was added to a partner (company).

Doing some testing we found out that this module was the one causing the issue. Do you know why it could be causing this?

You can see the behavior in this video (first how it should work, second how it works when this module is installed): https://youtu.be/p7qxvOutl_g

**Comment by edsersolis** [comment]
Sorry I thought the issue would go on the module, I mean the **save_readonly_fields** module.

https://github.com/alekglez/odoo-v10/tree/master/save_readonly_fields
